require('dotenv').config();
const authModel = require('../models/Auth');
const jwtModel = require('../models/JWTtokens');
const AdminModel = require('../models/Admin');
const StudentModel = require('../models/Student');
const LecturerModel = require('../models/Lecturer');
const NonAcademicStaffModel = require('../models/NonAcademicStaff');
const AcademicStaffModel = require('../models/AcademicStaff');
const { successResponse, errorResponse } = require('../utils/responseUtils');
const {hashPassword, comparePassword} = require('../utils/bcrypt');
const {generateAccessToken, generateRefreshToken} = require('../utils/jwt');
const jwt = require('jsonwebtoken');
